### ISSUE TITLE
Indenting Doesn't Work Properly for "latex" format

### ISSUE THREAD

**Issue by boyiguo1** [bcjaeger/tibbleOne_old#1]
Hi Dr. Jaeger,

Great work. Can't love it more. However, there is a minor issue with indenting when the output format is latex(don't know about html output, haven't tried).

When I replicated your example with _format_ argument as "latex", the pdf output generated from a Rmarkdown file doesn't indent right.  Following is the screen print:

![Screen Shot 2019-06-11 at 6 26 19 PM](https://user-images.githubusercontent.com/16565218/59313409-7779a080-8c76-11e9-98b2-de47efcb11c9.png)

Starting from the first group variable "Exposures", the indent starts to be incorrect.

**Comment by bcjaeger** [comment]
Hi Boyi, thanks! Can you clarify which row has incorrect indentation? I am aiming to indent each variable within a row, and each category within factors. Some factor variables within a group will have categories that are double indented. Is this what you are noticing? Maybe double indenting should be a user-defined input?

**Comment by boyiguo1** [comment]
Gotcha. I would personally say having a user-defined input for the double indented "grouped" variables is a better idea than having double indent as the default. 

I would assume that bolding the group name has the indication purpose that the following variables belong to that group. Depending on personal preferences, double-indenting after bolding the group name might be a little redundant for the indication purpose.

**Comment by bcjaeger** [comment]
Agreed. I will make this happen. Thanks again, Boyi!
