### ISSUE TITLE
issues w example code

### ISSUE THREAD

**Issue by rcantor13** [bcjaeger/tibbleOne_old#3]
per convo today...
bl_one = data %>%
  tibble_one(
    formula = ~ . | trt,
    include.freq = FALSE,
    include.pval = TRUE
  )

should be
bl_one = data %>%
  tibble_one(
    formula = ~ . | trt,
    include_freq = FALSE,
    include_pval = TRUE
  )

**Comment by bcjaeger** [comment]
Thanks! The readme code should now be updated and error-free.
